# Section 1: Getting Started

## Using Jupyter Notebooks

To evaluate a cell, highlight the cell and press Shift+Enter. 

To create a new cell, hit the + button in the toolbar above.

To create a cell for writing (as opposed to code) such as this one, highlight the cell and switch its type to "Markdown" in the dropdown menu above.

Some useful shortcuts:

In a cell, type esc, m, enter to go into change a cell to "Markdown".

Click to the left of a cell to enter Command Mode. In Command Mode, type:
    
    a   to add cell above
    
    b   to add cell below
    
    d,d to delete cell

Other useful shortcuts can be found here: http://maxmelnick.com/2016/04/19/python-beginner-tips-and-tricks.html

## Expressions

Python handles several types of expressions; e.g., string, numerical and list expressions. Evaluate the following cells.

In [1]:
2
# Numerical expression. 
# Note that statements following the pound symbol are not evaluated by Python.
# These are "comments" on your code. 

2

Note the comments included above. "Commenting" your code is EXTREMELY IMPORTANT. It will help others to follow your code. It will also help you when you go back to look at your code. 

Please include extensive comments on your code --- it may not be necessary for these first simple pieces of code, but it is good to get in the habit for when you start writing more complex code.

In [2]:
2.009 # Numerical expression

2.009

In [3]:
'abcd' # String expression. Note the quotation marks.

'abcd'

In [4]:
"abcd" # Double quotes also produces a string expression.

'abcd'

In [5]:
abcd 
# Without quotes, we get an error. 
# Python wants to treat this as a variable (see next section).

NameError: name 'abcd' is not defined

Remark: As you learn to code, you will spend a lot of time sorting through error messages. (In my experience, this is something that will persist even as you become a more proficient programmer.) 

It's a good idea to start paying attention to the structure of error messages. This is meant to help you fix your code. Google is your friend here!

In [6]:
[2,3,4,5] # List expression. Elements of the list are numerical expressions.

[2, 3, 4, 5]

In [7]:
['a','b','c','defg'] # A list expression whose elements are string expressions.

['a', 'b', 'c', 'defg']

In [8]:
['a',234] # Lists can contain different types of expressions.

['a', 234]

In [9]:
[['a','b','c'],[123],'1',2] # Lists can contain lists.

[['a', 'b', 'c'], [123], '1', 2]

## Operations

There are several operations that can be performed on each type of expression. Let's explore some possiblilites.

### Numerical Operations

In [10]:
2+3 # Addition

5

In [11]:
2 + 3 
# Spaces can be placed between arguments and operators.
# This has no effect on the output, but improves readability of the code.

5

In [12]:
2     +        3

5

In [13]:
2*3 # Multiplication

6

In [14]:
2**3 # Exponentiation

8

In [16]:
2**1000 # Large integer

10715086071862673209484250490600018105614048117055336074437503883703510511249361224931983788156958581275946729175531468251871452856923140435984577574698574803934567774824230985421074605062371141877954182153046474983581941267398767559165543946077062914571196477686542167660429831652624386837205668069376

In [19]:
(2**3)**2+45-7*6 # Combinations of operations. The usual order of operations applies.

67

### Exercise
By playing around with examples, determine the numerical operation performed by the following symbols:
/ // and %

### String Operations

In [27]:
'abcd'+'efgh' # Concatenation

'abcdefgh'

### List Operations

In [29]:
[1,2,3]+[4,5,6] # This is also concatenation, not vector addition!

[1, 2, 3, 4, 5, 6]

It makes sense that the above is concatenation, since it should make sense for lists of string expressions.

In [30]:
['a','b','c']+['cat','dog']

['a', 'b', 'c', 'cat', 'dog']

To perform vector operations, we need to use a package. A package is a collection of functions which need to be imported in order to use. A common package for linear algebra is called "numpy".

Note: Specialized packages need to be installed. Your installation of Anaconda came with numpy already installed.

In [31]:
import numpy # Use this command to import numpy

To get vectors, we enter them as a new type of expression: numpy arrays. 

In [32]:
numpy.array([1,2,3]) # Syntax: use the 'array' function from the package 'numpy'

array([1, 2, 3])

In [33]:
numpy.array([1,2,3])+numpy.array([4,5,6]) 
# Addition of numpy arrays works like vector addition.

array([5, 7, 9])

In [37]:
numpy.array(['a','b','c'])+numpy.array(['cat','dog']) # This does not make sense!

TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('<U3') dtype('<U3') dtype('<U3')

We can also represent matrices as numpy arrays and perform standard operations.

In [38]:
numpy.array([[1,2,3],[4,5,6]]) # A 2x3 matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
numpy.array([[1,2,3],[4,5,6]])+numpy.array([[1,0,0],[0,0,0]]) # Matrices can be added

array([[2, 2, 3],
       [4, 5, 6]])

In [40]:
numpy.array([[1,2,3],[4,5,6]])*numpy.array([[2,1,0],[0,1,0]]) 
# This is not matrix multiplication. It multiplies matrices entry-wise.

array([[2, 2, 0],
       [0, 5, 0]])

We will see below how to multiply matrices in numpy. This is demonstrated in the "Functions" section.
In general, we will use the numpy package extensively in this course.

## Variables
In the operations above, we typed out the expression in each line. It is much more economical to store expressions in variables.

In [45]:
a = 2 
# We define the variable "a" to represent the number 2.
# Notice that there is no output when we evaluate the cell.

In [42]:
b = 3

In [43]:
a*b # We can now perform operations on the variables

6

In [44]:
c = a**b # We can also define new variables by performing operations on the old ones
print(c)

8


Since an output is not automatically produced when we define a variable, we included the command 'print(c)' to display the value of the variable. 'print()' is an example of a function, which we will discuss below.

In [46]:
string1 = 'cat'
string2 = 'dog'
string1+string2

'catdog'

Virtually any string of numbers and letters can be used as a variable. Some symbols are reserved, however. For example, we can't use "2" to denote a variable. 

In [47]:
for = 5 
# 'for' is reserved to denote a command in a 'for loop'. This will be discussed below. 
# We get an error message if we attempt to use 'for' as a variable name. 

SyntaxError: invalid syntax (<ipython-input-47-50d8479d7dac>, line 1)

We can use variables to store any type of expression, such as lists or numpy arrays.

In [48]:
L = ['a','b','c','d']

In [49]:
L + ['e','f']

['a', 'b', 'c', 'd', 'e', 'f']

In [50]:
aa = numpy.array([[3,2],[1,1]])
bb = numpy.array([[2,2],[3,3]])
aa+bb

array([[5, 4],
       [4, 4]])

Variables can be redefined.

In [51]:
a = 1
a = 2
print(a)

2


Variables can be redefined recursively.

In [52]:
a = a+1
print(a)

3


Note that '=' doesn't play its usual mathematical role (otherwise the statement 'a=a+1' doesn't make sense). In Python, '=' has a directionality. The previous command should be read as 'the new value of 'a' is defined to be the previous value of 'a' plus 1.

In [53]:
L = L + ['p','q','r','s']
print(L)

['a', 'b', 'c', 'd', 'p', 'q', 'r', 's']


# Section 2: Functions, Conditionals, Loops
## Functions
Python has many built-in functions. These are rules which take one (or several) expression(s) to (an)other expression(s), possibly of different types.

In [54]:
len('abc') # For example, "len()" is a function which takes a string to an integer.

3

In [55]:
string1 = 'abc123xyz' # Functions can be applied to variables.
len(string1)

9

In [56]:
list1 = ['cat','dog','mouse'] # len() can also take a list as input
len(list1)

3

The "type()" function tells you what type of expression the input is.

In [57]:
type('abc')

str

In [58]:
type(2) # Notice that 2 is a numerical expression, but is in particular an integer.

int

In [59]:
type(2.09) # The numerical expression 2.09 is "float" type.

float

In [60]:
type([1,2,3])

list

In [61]:
type(numpy.array([1,2,3]))

numpy.ndarray

"str()" is a function which converts a numerical expression to a string.

In [62]:
str(12345)

'12345'

Functions can be composed

In [64]:
type(str(123))

str

Integers can be converted to floating point expressions via "float()".

In [65]:
float(2)

2.0

In [66]:
float('abc') # We can't convert strings to floats.

ValueError: could not convert string to float: 'abc'

## Defining functions

We will see many more examples of built-in functions below. Before that, we should discuss the real power of learning a programming language: the ability to define your own functions! 

The syntax that is used to define a function is illustrated below.
This tells us that we define a function named "square" with a single input "x". The function returns the input times itself. 

In [69]:
def square(x):
    return x*x
# The colon and "return" are crucial to define the function.

In [70]:
square(2)

4

In [71]:
a = 5
square(a)

25

We can define functions which take/return any combination of expression(s).

In [72]:
def add_exclamation_point(string): # Descriptive function names are highly recommended.
    return string+'!'

In [73]:
add_exclamation_point('hello')

'hello!'

In [74]:
add_exclamation_point(123) # This will give an error

TypeError: unsupported operand type(s) for +: 'int' and 'str'

### Exercise
Define a function "digits()" which takes a positive integer and returns its number of digits. Use it to compute the number of digits in 2**1000.

## More Built-In Functions

Let's now continue to explore some useful built-in functions.

### Functions on lists

Some functions have different syntax. For example, the 'append' function adds entries to lists as follows. Note that this syntax redefines the variable storing the list automatically.

In [75]:
L = ['a','b','c']
L.append('d')
print(L)

['a', 'b', 'c', 'd']


The 'pop' function removes the last term from a list.

In [76]:
L.pop()
print(L)

['a', 'b', 'c']


If we include a positive integer argument in 'pop' then it removes the term at the indicated index

In [77]:
L.pop(0) # Removes 'a' from the list.
print(L)

['b', 'c']


### Functions in the math package
Other basic numerical operations are not included in basic Python

In [79]:
sqrt(2)

NameError: name 'sqrt' is not defined

In [80]:
log(2)

NameError: name 'log' is not defined

To get access to these operations, we can import a package. In this case, we use the "math" package. 

In [81]:
import math

To use a function in the math package, we use the syntax "math.function()". This tells Python to use the function "function" from the package "math". For example:

In [82]:
math.sqrt(2)

1.4142135623730951

In [83]:
math.log(2)

0.6931471805599453

We will import packages frequently. Here are some tricks which are commonly used.

In [84]:
import math as ma # Use an abbreviation for the imported package

In [85]:
ma.sqrt(2)

1.4142135623730951

In [86]:
ma.log(2)

0.6931471805599453

Import specific functions from a package. We can abbreviate the function names if we want

In [87]:
from math import sqrt as sq

In [88]:
sq(2)

1.4142135623730951

Functions can be composed (as long as inputs/outputs make sense). Let's compose sq with our squaring function above.

In [89]:
sq(square(2))

2.0

In [91]:
square(sq(2)) # Here we see the numerical error in the square root function.

2.0000000000000004

### Functions in the numpy Package
Let's import numpy with an abbreviation. Common packages have "standard" abbreviations. That is, if you look at someone else's code, you will frequently see numpy imported as "np". 

In [95]:
import numpy as np

In [101]:
X = np.array([[1,2,3],[4,5,6]])
Y = np.array([[1,0],[1,1],[0,1]])
print(X)
print(Y)

[[1 2 3]
 [4 5 6]]
[[1 0]
 [1 1]
 [0 1]]


To multiply numpy arrays, we use the function "matmul" from the numpy package. This function takes two matrices of the appropriate dimensions and computes their product. To call the function, we use the syntax np.matmul().

In [102]:
np.matmul(X,Y)

array([[ 3,  5],
       [ 9, 11]])

'matmul' is also called using the '@' symbol.

In [107]:
X @ Y

array([[ 3,  5],
       [ 9, 11]])

Basically any standard operation from linear algebra is implemented in numpy.

In [131]:
Z = np.transpose(Y) # Transpose of a matrix
print(Z)

[[1 1 0]
 [0 1 1]]


In [132]:
np.linalg.det(X@Y) 
# Determinant of a (square) matrix. 
# Note that we call the determinant function from 'linalg'.
# This is a subcollection of functions (called a 'module') in the numpy package.

-12.000000000000005

Some other useful functions are "size" and "shape".

In [133]:
np.size(X) # Total number of entries

6

In [134]:
np.shape(X) # Dimensions of the array

(2, 3)

## Conditionals
We can write more interesting functions using conditionals. The output of the function can depend on whether or not a given condition holds. The syntax of a conditional is demonstrated by the following example.

In [135]:
def is_this_a_string(x):
    if type(x) == str:       # Notice the double equals and the colon
        return 'Yes'
    else:                  # Colon appears here too
        return 'No'

In [136]:
is_this_a_string(1)

'No'

In [137]:
is_this_a_string('abc')

'Yes'

There are several conditional expressions which can be used in an 'if' statement, such as <, != (not equal) or 'in'.

In [141]:
def contains_exclamation_point(string):
    if '!' in string:
        return 'Yes'
    else:
        return 'No'

In [142]:
contains_exclamation_point('abc!DD819')

'Yes'

In [143]:
contains_exclamation_point('abdcd0987')

'No'

Conditionals can involve multiple conditions by using "elif", which means "else, if".

In [144]:
def sign(x):  # Input is a float
    if x < 0:
        return 'The number '+str(x)+' is negative'
    elif x>0:
        return 'The number '+str(x)+' is positive'
    else:
        return 'The number '+str(x)+' is neither positive nor negative'  
    # In the last step we just use "else", since all other possibilities have been ruled out. 

In [145]:
print(sign(-1),sign(0),sign(1))

The number -1 is negative The number 0 is neither positive nor negative The number 1 is positive


Conditionals can be nested, and we can use combinations of conditions linked by logical connectors ('or', 'and', 'if', 'not', etc). The next function illustrates these ideas. The function takes a number and decides whether it lies between zero and one. We also create a custom error message if the user inputs something which isn't a number.

In [155]:
def is_between_zero_and_one(x):
    if type(x)==int or type(x)==float: # First conditional checks whether input makes sense
        if x > 0 and x < 1: # For a correct input, check whether it lies in the interval
            return 'Yes'
        else:
            return 'No'
    else:
        return 'Must enter a number!'

In [160]:
print(is_between_zero_and_one(0))
print(is_between_zero_and_one(0.1))
print(is_between_zero_and_one(0.99999))
print(is_between_zero_and_one(100))
print(is_between_zero_and_one('a'))

No
Yes
Yes
No
Must enter a number!


### Exercise

Write a function 'punctuation_check' which takes a string and returns the appropriate message:

"Contains exclamation point."

"Contains question mark."

"Contains both."

"Contains neither."

## Loops
Loops are an essential part of programming. They allow you to tell the computer to perform an operation repeatedly. The number of times to repeat the operation can be given specifically by a "for loop".

In [162]:
# First define a function to iterate in the 'for loop'
def collatz(n):
    if n % 2 == 0:
        return n//2
    else:
        return 3*n + 1

k = 17; # We initialize some value of k
for i in range(0,20): # "range" is a function which produces a list containing the integers within the specified range
  print(i, k) 
  k = collatz(k)
# Each iteration of this for loop prints the pair (i,k) then updates k. 
# The iteration is performed for i = 0,1,2,...,19

0 17
1 52
2 26
3 13
4 40
5 20
6 10
7 5
8 16
9 8
10 4
11 2
12 1
13 4
14 2
15 1
16 4
17 2
18 1
19 4


Some more basic examples of things you can do with for loops are shown below.

In [163]:
# We will compute 1 + 2 + ... + 10

sum = 0
for i in range(1,11):
    sum = sum + i
sum

55

In [165]:
# We will invest money at 3% interest for 10 years:

sum = 100
for i in range(0,11):
    print(i, sum)
    sum = 1.03*sum

0 100
1 103.0
2 106.09
3 109.2727
4 112.550881
5 115.92740743
6 119.4052296529
7 122.987386542487
8 126.67700813876162
9 130.47731838292447
10 134.39163793441222


In [166]:
# Let's compute the sum of the first n terms of the harmonic series
# 1 + 1/2 + 1/3 + ... + 1/n

sum = 0
for n in range(1,100):
    sum = sum + 1.0/n
sum

5.177377517639621

## While Loops
You can also tell Python to iterate an operation until a stopping condition is met. This is called a "while loop". Before you run a while loop, make sure that the stopping condition will actually be met! Otherwise you might cause your computer to crash.

In [167]:
# Let's find out how many terms we need in the harmonic series to get sum >= 10.
n = 1
sum = 0
while sum < 10:
    sum = sum + 1.0/n
    n = n + 1
n

12368

In [168]:
# Let's find out how long it takes to pay off a loan:

balance = 5000.00
annual_rate = 0.09
monthly_rate = math.exp(math.log(1 + annual_rate)/12.0) - 1
monthly_factor = 1 + monthly_rate
monthly_payment = 150
month = 0

print "Monthly rate: %1.4f\n" %(monthly_rate)

# Use d to format integers.  For example %4d means 
# format an integer in a 4-character space.  Use f
# to format floating point numbers.  For example,
# %4.2f means format a floating point number with
# 4 characters to the left of the decimal point
# and 2 to the right.

while balance > 0:
    print "%4d: %4.2f" %(month, balance)
    balance = monthly_factor*balance - monthly_payment
    month = month + 1
    
print "\n%d months to pay off your loan" %(month)

SyntaxError: invalid syntax (<ipython-input-168-eb8cb6925d98>, line 10)

We could define a function to perform the previous calculation for different parameters. We define our function to take in a loan balance, monthly payment and annual percentage rate. For the output, let's supress the monthly balances and just print the total amount of time to repay the loan.

Notice in the function definition, we write annual_rate=0.09. When evaluating the function, if we don't specify an annual rate then the function assumes the rate of 0.09.

In [17]:
def loan_repayment_time(balance,monthly_payment,annual_rate=0.09):
    monthly_rate = math.exp(math.log(1 + annual_rate)/12.0) - 1
    monthly_factor = 1 + monthly_rate
    month = 0
    while balance > 0:
        balance = monthly_factor*balance - monthly_payment
        month = month + 1

    return month  

We now test our function for various inputs:

In [72]:
print(loan_repayment_time(5000,150))
print(loan_repayment_time(4000,46.87,0.15))
# In the second example, the first monthly interest amount is $4000*0.15 ~ $46.8596.
# If the monthly payment is less than this, then the loan will never be repaid. 
# In this case, the while loop will never terminate. 
# To stop the calculation, hit the stop button in the menu above!

39
723


### Exercise

Define a function called 'isUnique' which takes a list and returns 'True' if the list contains no repeated entries and 'False' otherwise.

### Exercise

Define a function called 'uniquefy' which takes a list and removes all repeated entries.